blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/letmaik/pyvirtualcam2/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Idea
    url: https://github.com/letmaik/pyvirtualcam2/discussions/categories/ideas
    about: Discuss ideas here before creating a feature request.